export {
    ISignUpResponse,
    ISignInDto,
    IMeResponse,
    ISignInResponse,
    ISignUpDto,
    IChangePasswordDto,
    IChangeRoleDto,
    ISetAvatarDto,
    ISetDisplayNameDtoResponse,
    ISetDisplayNameDto,
    ISetFullNameDto,
    IApproveTaskDTO,
    IGetTaskDto,
    ICreateTaskDTO,
    ISwitchHeadFrameDto,
    ISwitchTryDto,
    INewTryDto,
    ICommitDto,
    IStartSolutionDto,
    IGetCurrentSolutionDto,
    IUpdateTaskDTO,
    IChangePasswordResponse,
    IChangeRoleResponse,
    ILogoutResponse,
    ISetAvatarResponse,
    ISetFullNameResponse,
    IGetTaskResponse,
    IGetTasksListResponse,
    IGetNotApprovedTasksListResponse,
    IApproveTaskResponse,
    ISwitchTryResponse,
    INewTryResponse,
    ICommitDtoResponse,
    IStartSolutionResponse,
    IGetCurrentSolutionResponse,
    ICreateTaskResponse,
    ISwitchHeadFrameResponse,
    IUpdateTaskResponse
} from './controllers';

export { authRouter } from './routes/auth-router';
export { lkRouter } from './routes/lk-router';
export { apiRouter } from './routes/api-router';
export { siteRouter } from './routes/site-router';
