export const QUERY_KEYS = {
    SIGN_UP: '/SIGN_UP_QUERY',
    SIGN_IN: '/SIGN_IN_QUERY',
    ME: '/ME_QUERY',
    LOGOUT: '/LOGOUT_QUERY',

    SET_NAME: '/SET_NAME_QUERY',
    SET_SURNAME: '/SET_SURNAME_QUERY',
    SET_PATRONYMIC: '/SET_PATRONYMIC_QUERY',
    SET_DISPLAY_NAME: '/SET_DISPLAY_NAME_QUERY'
};

export const QUERY_WITHOUT_AUTH = [QUERY_KEYS.SIGN_UP, QUERY_KEYS.SIGN_IN];
