export const QUERY_KEYS = {
    SIGN_UP: '/SIGN_UP_QUERY',
    SIGN_IN: '/SIGN_IN_QUERY',
    ME: '/ME_QUERY',
    LOGOUT: '/LOGOUT_QUERY',

    SET_FULL_NAME: '/SET_FULL_NAME_QUERY',
    SET_DISPLAY_NAME: '/SET_DISPLAY_NAME_QUERY',
    SET_AVATAR: '/SET_AVATAR_QUERY',
    CHANGE_PASSWORD: '/CHANGE_PASSWORD_QUERY',
    CHANGE_ROLE: '/CHANGE_ROLE_QUERY'
};

export const QUERY_WITHOUT_AUTH = [QUERY_KEYS.SIGN_UP, QUERY_KEYS.SIGN_IN];
